spring.application.name=Spring-Boot-REST-CRUD-Employee

#Turn off the Spring-Boot banner
spring.main.banner-mode=off

#JDBC connectivity properties
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=springstudent
spring.datasource.password=springstudent#1234

# Reduce the logging level. Set Logging level to warn
logging.level.root=warn

#logging level for hibernate
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace
