# HTTP server port
server.port=7071

# Context path of the application
server.servlet.context-path=/spring-boot-demo
server.servlet.session.timeout=15m

#define my custom properties
coach.name=Mickey The Mouse
team.name=The Mouse Club

logging.level.org.springframework=INFO
logging.level.org.hibernate=TRACE
logging.level.curiouscoder=INFO

#logging.file=log4j.properties
